# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 20:58
from __future__ import unicode_literals

import SAM2017.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to=SAM2017.models.get_upload_file_name)),
                ('authors', models.ManyToManyField(to='SAM2017.Author')),
            ],
        ),
    ]
